# Generated by Django 4.1.4 on 2022-12-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image_s3_path",
            field=models.ImageField(null=True, upload_to="innotter/media"),
        ),
    ]
