# Generated by Django 4.1.4 on 2022-12-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
