# Generated by Django 4.1.4 on 2022-12-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_delete_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="image",
            field=models.ImageField(null=True, upload_to="innotter/media"),
        ),
    ]
