# Generated by Django 4.1.4 on 2023-01-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_alter_page_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
