# Generated by Django 4.1.4 on 2023-01-26 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0002_alter_post_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="users_liked",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="liked_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Liked posts",
            ),
        ),
    ]
